baseurl:      http://loveseven.github.io
pygments:     true
markdown:     rdiscount
permalink:    /posts/:year-:month-:day-:title.html
title:        Seven
description:  Seven的个人站点,记录心情与知识。
keywords:     Seven,个人站点,博客,心情,知识,编程
author:       Seven
email:        yihongyuelan@gmail.com
github:       http://github.com/loveseven
